apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  MONGO_URI: "mongodb+srv://freshkite:freshkite@cluster0.cjtnere.mongodb.net/todo?retryWrites=true&w=majority"
  PORT: "5000"
  JWT_SECRET: "todo_secret_key"